=== MikhailMakar/JavaCore_August_2021/src/main/resources/xmlDocs/companiesXSD.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.epam.tc.com/note"
        xmlns:tns="http://www.epam.tc.com/note">

    <element name="company" >
        <complexType>
            <sequence>
                <element name="name" type="string"/>
                <element name="offices" type="tns:offices"
                         minOccurs="0"
                         maxOccurs="unbounded" />
            </sequence>
        </complexType>
    </element>

    <complexType name="offices">
        <sequence>
            <element name="office" type="tns:office"
                     minOccurs="0"
                     maxOccurs="unbounded"
            />
        </sequence>
    </complexType>

    <complexType name="office">
        <sequence>
            <element name="employees" type="tns:employees"
                     minOccurs="0"
                     maxOccurs="unbounded"/>
        </sequence>
        <attribute name="floor" type="integer"/>
        <attribute name="room" type="integer"/>
    </complexType>

    <complexType name="employees">
        <sequence>
            <element name="employee" type="tns:employee"
                     minOccurs="1"
                     maxOccurs="unbounded"
            />
        </sequence>
    </complexType>

    <complexType name="employee">
        <attribute name="name" type="string" use="required"/>
        <attribute name="job" type="string"/>
        <attribute name="age" type="integer"/>
    </complexType>
</schema>

=== MikhailMakar/JavaCore_August_2021/src/main/resources/xmlDocs/companies.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<companies:company xmlns:companies="http://www.epam.tc.com/note"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:schemaLocation="http://www.epam.tc.com/note companiesXSD.xsd">
    <name>IT-Heaven</name>
    <offices>
        <office floor='1' room="1">
            <employees>
                <employee name="John" job="Middle Software Developer"/>
                <employee name="Ivan" job="Junior Software Developer"/>
                <employee name="Franklin" job="Junior Software Developer"/>
            </employees>
        </office>
        <office floor="1" room="2">
            <employees>
                <employee name="Herald" job="Middle Software Developer" age="22"/>
                <employee name="Adam" job="Middle Software Developer"/>
                <employee name="Leroy" job="Junior Software Developer"/>
            </employees>
        </office>
    </offices>
</companies:company>
